# Generated by Django 5.0.1 on 2026-02-11 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_registered', 'Nouvel utilisateur enregistré'), ('user_login', 'Connexion utilisateur'), ('product_created', 'Produit créé'), ('product_updated', 'Produit modifié'), ('product_voted', 'Vote produit'), ('order_created', 'Commande créée'), ('event_created', 'Événement créé'), ('chat_message', 'Message chat'), ('other', 'Autre')], max_length=50, verbose_name="Type d'action")),
                ('description', models.TextField(verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'activité",
                'verbose_name_plural': "Logs d'activité",
                'ordering': ['-timestamp'],
            },
        ),
    ]
