# Generated by Django 5.0.1 on 2026-02-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToxicityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sulfur_level', models.FloatField(verbose_name='Taux de soufre (%)')),
                ('carbon_level', models.FloatField(verbose_name='Taux de carbone (%)')),
                ('oxygen_level', models.FloatField(verbose_name="Taux d'oxygène (%)")),
                ('temperature', models.FloatField(verbose_name='Température (°C)')),
                ('pressure', models.FloatField(verbose_name='Pression (bar)')),
                ('alert_level', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Attention'), ('danger', 'Danger'), ('critical', 'Critique')], default='normal', max_length=20, verbose_name="Niveau d'alerte")),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Donnée de toxicité',
                'verbose_name_plural': 'Données de toxicité',
                'ordering': ['-timestamp'],
            },
        ),
    ]
